spring:
  liquibase:
    change-log: classpath:/db/changelog-profiles/changelog-master.xml
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://app:8760/eureka/