server:
  port: 8861
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8860/eureka/
spring:
  liquibase:
    change-log: classpath:/db/changelog-profiles/changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  application:
    name: main-app